### ISSUE TITLE
Viewing full test data

### ISSUE THREAD

**Issue by chuckan13** [neilwalkinshaw/mintframework#10]
From the papers associated with this project, it seems like one of the purposes of mintframework is to generate better testing data (for ML algorithms for example). However, I can't seem to figure out how to extract the test data generated with mintframework. Is that feature supported?

**Comment by neilwalkinshaw** [comment]
Thanks @chuckan13, It is supported, but I completely agree that this aspect hasn't been adequately documented.

I am currently having to handle a significant workload, but will try to address this query within the next two weeks.

Best wishes,

Neil

**Comment by chuckan13** [comment]
In the meantime, could you point me towards any papers of yours that describe how the traces in the input files in more detail? I'm a bit confused looking at them because in your paper "Black-Box Test Generation from Inferred Models", you describe the input files differently (JSON files).

**Comment by chuckan13** [comment]
Hi! Just wanted to follow up on this. I'm still very interested in the test generation feature. Could you share any updates on this?

**Comment by neilwalkinshaw** [comment]
Hi @chuckan13 - sure, glad to! Perhaps we can take this onto email. Can you send me an email (n.walkinshaw@sheffield.ac.uk) with the details of the sort of system you're trying to test (particularly what sort of interface it has)? Then I can try to talk you through how to use MINT (if it's possible for that system...).

**Comment by neilwalkinshaw** [comment]
Hi Chuckan13 - I have just updated the instructions on the README, which should hopefully help. The test inputs are written to a file by default.
